### ISSUE TITLE
Add Rake Tasks to gem

### ISSUE THREAD

**Issue by cdenneen** [rnelson0/puppet-generate-puppetfile#78]
Can you add rake tasks to this gem?

Similar to `https://github.com/rodjek/puppet-lint/tree/master/lib/puppet-lint/tasks`

Then you could do the following in `.sync.yml`:

```yaml
Rakefile:
  requires:
    - puppet-lint/tasks/puppet-lint:
      require: puppet-lint/tasks/puppet-lint
      conditional: Bundler.rubygems.find_name('puppet-lint').any?
    - generate-puppetfile/tasks/generate_puppetfile:
      require: generate-puppetfile/tasks/generate_puppetfile
      conditional: Bundler.rubygems.find_name('generate-puppetfile').any?
    - generate-puppetfile/tasks/generate_fixturesfile:
      require: generate-puppetfile/tasks/generate_fixturesfile
      conditional: Bundler.rubygems.find_name('generate-puppetfile').any?
```
